# Generated by Django 3.1.2 on 2021-03-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0003_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
